# NOTE: Set your working directory to the repository root before running this script.


tissue.names=read.csv("GTEx/data/tissuenames.csv", header = T)
#top5=c(48,40,33,6,1)
#get the top five tissues by sample size
#tissues.vec=tissue.names[top5, 2]
tissues.vec=rev(tissue.names[, 2])
tissues.vec2 = rev(tissue.names[,3])
#library('psych')
#library('tmvtnorm')
#library('ff')
#library('propagate')
library('MRGN')
#library('qvalue')
#find the trios with only lincRNA or protein_coding genes:::



#read in trio gene type labels from biomart merged table:
bmart=read.table(file="GTEx/data/mart_export_merged_lncRNA_fixed.txt", sep = "\t", header = T)
#convert pseudogene element names to "pseudogene"
#pseudo.idx=which(grepl("pseudogene", bmart$Gene.type)==TRUE)
#lnc.idx=which(grepl("lncRNA", bmart$Gene.type)==TRUE)
#bmart$Gene.type[pseudo.idx]="pseudogene"
#bmart$Gene.type[lnc.idx]="lncRNA"

#functions needed:
#==============================================================
#use biomart data to find the gene types for cis/trans targets
get.types=function(x, bm.data){
  types=NULL
  loc=NULL
  for(i in 1:2){
    loc[i]=match(x[i], bm.data$Gene.stable.ID)
    types[i]=bm.data$Gene.type[loc[i]]
  }

  return(types)

}
#==============================================================
#find which trios have one or both genes as either protein coding or lncRNA
find.types=function(x){
  idx=NULL
  if(isTRUE(sum(x==c("protein_coding","lncRNA"))==2)){
    idx=TRUE
  }else if(isTRUE(sum(x==c("lncRNA","protein_coding"))==2)){
    idx=TRUE
  }else if(isTRUE(sum(x=="protein_coding")==2)){
    idx=TRUE
  }else if(isTRUE(sum(x=="lncRNA")==2)){
    idx=TRUE
  }else{
    idx=FALSE
  }
  return(idx)
}
#==============================================================





#this function extracts only trios with protein coding or lncRNA and then performs the PC
#selection on those trios
for(i in 1:length(tissues.vec)){

  print(paste0("Loading Data For...",tissues.vec[i]))
  # NOTE: External GTEx V8 data path - update for your environment
  PCs.matrix=loadRData(fileName=paste0("GTEx/external_data/GTEx_version_8/",tissues.vec[i],"_AllPC/PCs.matrix.",tissues.vec[i],".RData"))
  # NOTE: External GTEx V8 data path - update for your environment
  data.all.unique.snps=loadRData(fileName=paste0("GTEx/external_data/GTEx_version_8/",tissues.vec[i],
                                                 "_AllPC/data.snp.cis.trans.final.",tissues.vec[i],".V8.unique.snps.RData"))
  
  print('Extracting known covariates...')
  # NOTE: External GTEx V8 data path - update for your environment
  kc = t(read.table(paste0("GTEx/external_data/GTEx_version_8/GTEx_Analysis_v8_eQTL_covariates/",
                    tissues.vec2[i], '.v8.covariates.txt'), header = T, sep="\t", row.names = 1))
  kc = kc[,(dim(kc)[2]-2):dim(kc)[2]]
  print(head(kc))
  
  X=cbind(seq(1,ncol(data.all.unique.snps)-2,3), seq(3,ncol(data.all.unique.snps),3))
  Z=split(X,seq(nrow(X)))
  all.unq.snps.ldf=lapply(Z, function(x,data){data[,x[1]:x[2]]}, data=data.all.unique.snps)


  #get list of cis and trans gene names for matching in biomart data
  genes.list=lapply(all.unq.snps.ldf, function(x,i,j){colnames(x[,i:j])}, i=2, j=3)
  #get the list of gene types of cis and trans for each trio
  gene.types=lapply(genes.list, get.types, bm.data=bmart)
  #convert to an n X 2 data frame
  gene.types2=do.call("rbind.data.frame", gene.types)
  colnames(gene.types2)=c("cis.gene.type","trans.gene.type")

  #number of trios with an unmatched gene types
  print(paste0("Trios with at least one entry unable to be matched to a gene type for ",tissues.vec[i]))
  which.unmatched=apply(gene.types2, 1, is.na)
  sum.TF=apply(which.unmatched, 2, sum)
  print(which(sum.TF>=1))

  #get the trios that have one or more genes being a pseudogene
  print(paste0("indentifying lncRNA and protein coding trios for ",tissues.vec[i], " ..."))
  idx.prot.lnc=apply(gene.types2, 1,find.types)
  print(paste0("found ", sum(idx.prot.lnc), "trios for ", tissues.vec[i]))

  print(paste0("checkpoint...make sure only protein coding and lncRNA for ", tissues.vec[i]))
  print(apply(gene.types2[which(idx.prot.lnc),], 2, function(x) summary(as.factor(x))))
  #keep only protein coding and lncRNA and rebind original list back into dataframe
  all.unq.snps.ldf.pl.only=do.call("cbind",all.unq.snps.ldf[which(idx.prot.lnc)])
  #undo the colnames generated by do.call
  colnames(all.unq.snps.ldf.pl.only)=make.unique(colnames(all.unq.snps.ldf.pl.only))
  save(all.unq.snps.ldf.pl.only, file = paste0("GTEx/data/trios_subset_data/all.data.unqiue.snps.pclrna.only.",tissues.vec[i],".RData"))

  #now run the PC selection on the remaining trios:::
  #colnames(all.unq.snps.ldf.pl.only) <- make.unique(colnames(all.unq.snps.ldf.pl.only)) #duplicated colnames

  All.Pvalues <- list()
  List.significant.asso1 <- list()

  print(paste0("Getting PC List For...",tissues.vec[i]))

  # List.significant.asso1=get.conf(all.unq.snps.ldf.pl.only, PCscores = PCs.matrix, return.list = T, blocksize = 1000,
  #                                method = "regression", filter_int_child = T, selection_fdr = 0.05, filter_fdr = 0.1,
  #                                save.list = paste0("GTEx/data/Lists_asso_PCS/List.significant.asso1.",tissues.vec[i]))$sig.asso.pcs

  List.significant.asso1=get.conf.trios(trios = all.unq.snps.ldf.pl.only, cov.pool = PCs.matrix, blocksize = 200,
                                        filter_int_child = T, selection_fdr = 0.05, filter_fdr = 0.1, adjust_by = 'individual', save.list = T,
                                        save.path = paste0("GTEx/data/Lists_asso_PCS/List.significant.asso1.",tissues.vec[i]))$sig.asso.covs


  #List.significant.asso1 = List.significant.asso1[which(idx.prot.lnc)]
  print("Found list of associated PCs")
  print(lapply(List.significant.asso1[1:5], head))
  print(paste0("Saving List For...",tissues.vec[i]))
  #save(List.significant.asso1, file=,".RData"))


  # columns number for trios
  start.col <- seq(1,dim(all.unq.snps.ldf.pl.only)[2],3)
  end.col <- seq(3,dim(all.unq.snps.ldf.pl.only)[2],3)

  trios <- dim(all.unq.snps.ldf.pl.only)[2]/3
  print(paste0("Total number of trios for ",tissues.vec[i]))
  print(trios)

  #Match.PCs.col <- list()
  #List.Match.significant.trios <- list()
  data.sets=list()

  print(paste0("extracting PCs for each trio...",tissues.vec[i]))
  for (ii in 1:trios) {
    # data
    data <- all.unq.snps.ldf.pl.only[,start.col[ii]:end.col[ii]]
    # # search in each PCs
    # for (m1 in 1:(dim(PCs.matrix)[1]-1)) {
    #   Match.PCs.col[[m1]] <- intersect(colnames(data),colnames(all.unq.snps.ldf.pl.only)[List.significant.asso1[[m1]][[1]]])
    # }
    # List.Match.significant <- which(sapply(Match.PCs.col, function(e) length(e)!=0))
    # List.Match.significant.trios[[ii]] <- List.Match.significant
    # #pre-allocate all trios to a list for ease of use in analysis
    if(length(List.significant.asso1[[ii]])!=0)
    {
      data.withPC <- cbind.data.frame(data, kc, PCs.matrix[,List.significant.asso1[[ii]]])
      colnames(data.withPC) <- c(colnames(data), colnames(kc), 
                                 paste("PC",List.significant.asso1[[ii]],sep=""))
    }
    else
    {
      data.withPC <- cbind.data.frame(data, kc)
      colnames(data.withPC) <- c(colnames(data), colnames(kc))
    }
    data.sets[[ii]]=data.withPC
  }

  print(head(lapply(data.sets, function(x){colnames(x)})))
  save(List.significant.asso1, file=paste0("GTEx/data/list_matched_sig_trios/List.Match.significant.trios.",tissues.vec[i],".RData"))
  save(data.sets, file=paste0("GTEx/data/final_trios_with_PCs/data.with.PCs.",tissues.vec[i],".RData"))



}



